SMOKE_CONFIG = {'seed': 27, 'device': 'cpu', 'exp_name': 'DQN_Cartpole',
                'env': {'name': 'CartPole-v1', 'num_envs': 4, 'gamma': 0.99},
                'agent': {'name': 'DoubleDqn', 'initial_no_learn_steps': 100, 'update_freq': 5,
                          'target_update_freq': 6000, 'num_updates': 2,
                          'buffer': {'name': 'ExperienceReplay', 'buffer_size': 10000, 'batch_size': 1024}},
                'trainer': {'num_steps': 100000, 'eval_freq': 100, 'eval_num_episodes': 10},
                'policy': {'name': 'EpsilonPolicy',
                           'epsilon_scheduler': {'name': 'annealed_epsilon', 'end_epsilon': 0.01,
                                                 'anneal_finished_step': 200}},
                'vfa': {'name': 'NeuralNetworkVfa', 'network': {'name': 'SimpleNeuralNetwork', 'num_hidden': 64},
                        'loss_fn': {'name': 'SmoothL1Loss'},
                        'optimizer': {'name': 'RMSprop', 'lr': 0.48535532171538653}, 'clip_grad_val': 0.0},
                'logger': {'name': 'RayTuneLogger', 'log_every': 10}}
